---
- name: start redis instances
  hosts: dbservers
  become: yes
  become_user: redis
  tasks:
    - name: starting all the primary and replica instances of a cluster
      command: "{{item}}"
      with_items: 
        - "redis-server /etc/redis/redis_6000.conf"
        - "redis-server /etc/redis/replica_6001.conf"
        - "redis-server /etc/redis/redis_7000.conf"
        - "redis-server /etc/redis/replica_7001.conf"
        - "redis-server /etc/redis/redis_8000.conf"
        - "redis-server /etc/redis/replica_8001.conf"
        #- "redis-cli -h vm-redis -p 6000 -a redis123 --cluster create vm-redis:6000 vm-redis:7000 vm-redis:8000 vm-redis:6001 vm-redis:7001 vm-redis:8001 --cluster-replicas 1"